name: $(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscriptionId: '82fb79bf-ee69-4a57-a76c-26153e544afe'
  subscription: 'JJ Microsoft Azure Internal Consumption (82fb79bf-ee69-4a57-a76c-26153e544afe)'

stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: ImagePacker
      displayName: Build image
      steps:
      - task: PackerBuild@1
        displayName: 'Build immutable image'
        inputs:
          ConnectedServiceName: $(subscription)
          managedImageName: 'jjvmimagelx-$(Build.BuildNumber)'
          location: westeurope
          storageAccountName: jjpackerstorage
          azureResourceGroup: jjpacker-rg
          baseImage: 'Canonical:UbuntuServer:18.04-LTS:linux'
          packagePath: packer
          deployScriptPath: deploy.sh
      - task: PublishBuildArtifacts@1
        displayName: 'Publish ARM template to drop'
        inputs:
          PathtoPublish: 'template'
  - stage: DeployDEV
    displayName: Deploy to DEV
    dependsOn: Build
    variables:
      - group: jjpacker-DEV
    jobs:
      - deployment: DeployDEV
        displayName: Deploy ARM template
        environment: 'jjpacker-DEV'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: Delete existing VM in resource group
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: $(subscription)
                  subscriptionId: $(subscriptionId)
                  action: 'DeleteRG'
                  resourceGroupName: 'jjdevv2vmapplx-rg'
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: Deploy new VM in resource group
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: $(subscription)
                  subscriptionId: $(subscriptionId)
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'jjdevv2vmapplx-rg'
                  location: 'West Europe'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/drop/deploy-vm.json'
                  csmParametersFile: '$(Pipeline.Workspace)/drop/deploy-vm.parameters.json'
                  overrideParameters: '-adminPassword $(adminPassword) -imageName jjvmimagelx-$(Build.BuildNumber)'
                  deploymentMode: 'Incremental'                  